adapt BAIDU_RUNTIME
cocos-creator-packages/baidu-adapter pull request #1
Opened 2018-12-01 08:30 UTC by umbrellaPP

适配 百度小游戏 runtime

目前完成主域的基本适配工作
开放数据域的渲染逻辑是在构建的时候打包进去的。
所以这部分适配工作需要在完成编辑器构建之后，才能进行

2018-12-03 07:09 UTC, pandamicro requested changes

2018-12-03 07:09 UTC, pandamicro commented on baidugame/libs/adapter/engine/Loader.js
> +cc.loader.loader.addHandlers({
loadImage 也有定制，从 https://github.com/cocos-creator/engine/pull/3582 迁移到这里

2018-12-03 08:53 UTC, pandamicro requested changes

2018-12-03 08:53 UTC, pandamicro commented on baidugame/game.js
> +require('./libs/adapter/engine/Device');  // adapt CCSys.js here
Provide Device related infos

2018-12-03 08:53 UTC, pandamicro commented on baidugame/libs/adapter/engine/Device.js
> +            audioSupport: this.getAudioSupport(),
去除不必要的函数接口

2018-12-03 09:39 UTC, pandamicro approved these changes

2018-12-03 09:40 UTC, merged

2018-12-07 06:10 UTC, dumganhar commented
不服别的，就服 百度、头条 会抄。